### ISSUE TITLE
digitos en contabilidad

### ISSUE THREAD

**Issue by deook** [anfix/anfix-partners#2]
Aunque en la web de anfix tengas la contabilidad con 10 digitos desde aquí al contabilizar la factura desde export no permite mas que ocho, sale un error

**Comment by patricia-ganan** [comment]
La funcionalidad de ampliar el número de dígitos no está disponible vía api. Lo mejor es que en estos casos realices el  upgrade de dígitos contables desde la propia aplicación ya que es un caso puntual y no habitual. Si dispones de un plan que tenga contabilidad, desde la gestión de la empresa podrás realizar esta operación. Si tienes dudas sobre cómo realizar el proceso, puedes ponerte en contacto con nuestro equipo de Atención al Cliente (soporte@anfix.com) para que te de las indicaciones oportunas.
