### ISSUE TITLE
Cuentas contables en clientes

### ISSUE THREAD

**Issue by deook** [anfix/anfix-partners#3]
Al registrar un cliente no registra la cuenta contable correctamente

**Comment by patricia-ganan** [comment]
Esta api no está pensada para crear clientes asignando cuentas contables. Para acceder a esa funcionalidad deberás usar directamente la api de Ventas https://s3-eu-west-1.amazonaws.com/anfix/api/api-anfix-ventas-simplificada-v1.3.zip
